[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "node ./node_modules/vite/bin/vite.js preview --host 0.0.0.0 --port ${PORT:-3000}"
